# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FactCheck' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FactCheck
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  target 'FactCheckTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FactCheckExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FactCheckExtension
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'CryptoSwift'

end
